### PR TITLE
Added fix to the "F$Chain unlink twice" bug.

### PR DESCRIPTION
**Pull request by DrPitre**
This incorporates the fix that @strickyak came up to get around the "`F$Chain` unlinking twice" bug. His original fix added 8 bytes; I was able to refactor the code in a way that saves that 8 byte growth by reusing the same `F$Unlink` code for both user and system state. HOWEVER, this required that I perform the F$Unlink AFTER masking interrupts instead of before masking like the original code had it. Other than preventing preemption and delaying interrupts during the unlinking, I can't think of any regression that this might cause. Feel free to try to optimize this code even further and minimize the masked interrupt code as well.

### CODE REVIEW

**Comment by DrPitre** [comment]
To reproduce the bug, do the following:

1. Boot into NitrOS-9 Level 1 without this kernel fix.
2. At the shell, type: `shell` and press ENTER. This creates a child shell process.
3. At the child shell, type `ex` and press ENTER. You'll see an `ERROR #215` or `ERROR #216` followed by the prompt of the parent of the shell.
4. At the parent shell prompt, type any command (e.g. `procs`) and press ENTER.
5. The computer will likely give some odd output and then become unstable and eventually crash.

**What's happening?**

In NitrOS-9 Level 1, the shell module is not part of the boot file -- it's forked by the `SysGo` module at startup where it's given a link count of 1. When you type `shell` in step 2 above, shell uses the `F$Fork` system call to create the child process, and the link count goes to 2. When you type `ex` in step 3 above, the shell uses the `F$Chain` system call to chain into a new process. `F$Chain` calls `F$Unlink` to unlink the module (shell) and then attempts to chain to the command following the `ex`. . Since nothing follows the `ex` command, `F$Chain` indicates an error and calls `F$Exit` which calls `F$Unlink` again. Now the link count is 0, and `F$Unlink` deallocates the memory that `shell` occupied, yet `shell` is the parent process. Any subsequent `F$Fork` from the parent shell that requires an `F$Load` causes a crash because the module being loaded lays on top of the memory that `shell` occupied.

**The Fix**
To get around the effects of unlinking twice, the fix is for `F$Chain` to only call `F$Unlink` on the module *IF* the `F$Link` or `F$Load` succeeded, thus ensuring that the `F$Exit` call won't be made and the link count only goes down by 1.

**Comment by strickyak** [comment]
Boisy, hold off for a couple of days.
Tonight I tried briefly with my emulator, and I'm seeing an error
     `RETURN ERROR: $d7(E$BPNam  :Bad Path Name): OS9KERNEL1 OS9$03 <F$Fork> {Module/file='Shell' param="{13}" lang/type=1 pages=0}`
that I need to look into more deeply than I can do tonight.
Tomorrow I'm flying back to Cali, and I may be able to figure it out on the plane.

**Comment by strickyak** [comment]
(* note to self: `/sy/doing_os9/gomar/H.bug.30` *)

**Comment by strickyak** [comment]
I found what I was doing wrong, and gotten past that...

and I've confirmed the fix works for me, in my emulator, 
in the simple "shell ... ex" scenario.   I reproduced failure
without the fix, and success with it.

LGTM

**Comment by DrPitre** [comment]
@strickyak, thanks for confirming. For the record, can you approve the pull request?

**Comment by strickyak** [comment]
sorry, boarding in AGS, I'll figure out where the approval button is in ATL in an hour or so

**Review by Deek — APPROVED** [review]
Looks good to me 😊

**Review by strickyak — APPROVED** [review]
Approval, and thanks for staging these.

**Pull request merged**
